In [1]:
import pandas as pd
import duckdb

In [2]:
con = duckdb.connect()

con.execute("""
CREATE OR REPLACE TABLE paysim AS
SELECT *
FROM read_csv_auto('../data/paysim_transactions.csv');
""")

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

In [3]:
con.execute("SELECT COUNT(*) AS total_rows FROM paysim").df()

   total_rows
0     6362620

In [4]:
con.execute("""
SELECT *
FROM paysim
LIMIT 5;
""").df()

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
0,1,PAYMENT,9839.64,C1231006815,170136.0,160296.36,M1979787155,0.0,0.0,0,0
1,1,PAYMENT,1864.28,C1666544295,21249.0,19384.72,M2044282225,0.0,0.0,0,0
2,1,TRANSFER,181.00,C1305486145,181.0,0.00,C553264065,0.0,0.0,1,0
3,1,CASH_OUT,181.00,C840083671,181.0,0.00,C38997010,21182.0,0.0,1,0
4,1,PAYMENT,11668.14,C2048537720,41554.0,29885.86,M1230701703,0.0,0.0,0,0

In [11]:
con.execute("""
SELECT type, COUNT(*) AS total_transactions,
                SUM(isFraud) AS fraud_transactions,
          round(SUM(isFraud) * 1.0 / COUNT(*), 4) AS fraud_rate
FROM paysim
GROUP BY type
            order by fraud_rate DESC
""").df()

       type  total_transactions  fraud_transactions  fraud_rate
0  TRANSFER              532909              4097.0      0.0077
1  CASH_OUT             2237500              4116.0      0.0018
2     DEBIT               41432                 0.0      0.0000
3   PAYMENT             2151495                 0.0      0.0000
4   CASH_IN             1399284                 0.0      0.0000